CREATE TABLE IF NOT EXISTS inspection_terceiros (
  id SERIAL PRIMARY KEY,
  date TEXT,
  inspector TEXT,
  company_name TEXT,
  worker_name TEXT,
  worker_type TEXT,
  received_epi_instructions TEXT,
  received_training TEXT,
  participated_integration TEXT,
  has_necessary_epis TEXT,
  needs_work_permit TEXT,
  activity_description TEXT,
  accompanier_name TEXT,
  accompanier_role TEXT,
  photo_location TEXT,
  photo_nonconformity TEXT,
  observations TEXT,
  tech_signature TEXT,
  tech_name TEXT,
  tech_role TEXT,
  inspected_signature TEXT,
  inspected_name TEXT,
  inspected_role TEXT
);
