ALTER TABLE trainings 
ADD COLUMN IF NOT EXISTS title TEXT,
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS enrolled INTEGER DEFAULT 0,
ADD COLUMN IF NOT EXISTS photo_url TEXT,
ADD COLUMN IF NOT EXISTS comments TEXT,
ADD COLUMN IF NOT EXISTS rating_content TEXT,
ADD COLUMN IF NOT EXISTS rating_visual TEXT,
ADD COLUMN IF NOT EXISTS rating_sound TEXT,
ADD COLUMN IF NOT EXISTS rating_instructor TEXT,
ADD COLUMN IF NOT EXISTS rating_understanding TEXT;
